---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/distributorntwkdb'
    username: root
    password: Jinesh@123
network:
  businessType: retail
  locationType: local
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9091/eureka,http://localhost:9092/eureka
...